export SVN_EDITOR=emacs

# command alias
alias rm='rm -i'
alias ll='ls -l'
alias rgrep='grep -r'
alias s='python -m SimpleHTTPServer'
alias ec='emacsclient -t -a ""'
alias ls='ls --color=auto'

export CDPATH=.:/usr/local/maui/

# don't put duplicate lines in the history. See bash(1) for more options
# don't overwrite GNU Midnight Commander's setting of `ignorespace'.
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups
# ... or force ignoredups and ignorespace
export HISTCONTROL=ignoreboth
export EDITOR='emacsclient -t -a ""'
